version: "2.4"

services:
    reconstruction_zookeeper:
        image: 'docker.io/bitnami/zookeeper:3-debian-10'
        container_name: reconstruction_zookeeper
        ports:
            - '2181:2181'
        volumes:
            - "reconstruction_zookeeper_data:/data:rw"
            - "reconstruction_zookeeper_datalog:/datalog:rw"
        environment:
        ALLOW_ANONYMOUS_LOGIN: "yes"
        restart: unless-stopped
        networks:
            - reconstruction_network

    reconstruction_kafka:
        image: 'docker.io/bitnami/kafka:2-debian-10'
        container_name: reconstruction_kafka
        environment:
            KAFKA_CFG_LISTENERS: "EXTERNAL://:9093,PLAINTEXT://:9092"
            KAFKA_CFG_ADVERTISED_LISTENERS: "EXTERNAL://${HOST_IP}:9093,PLAINTEXT://:9092"
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            KAFKA_CFG_ZOOKEEPER_CONNECT: "reconstruction_zookeeper:2181"
            ALLOW_PLAINTEXT_LISTENER: "yes"
        ports:
            - "${HOST_IP}:9093:9093"
        volumes:
            - "reconstruction_kafka_data:/bitnami/kafka:rw"
        depends_on:
            - reconstruction_zookeeper
        restart: unless-stopped
        networks:
            - reconstruction_network

    reconstruction_service:
        build: ./app
        container_name: "reconstruction_service"
        command: bash -c ./3D-reconstruction
        ports:
            - "${HOST_IP}:7200:7300"
        volumes:
            - "/tmp/.X11-unix:/tmp/.X11-unix"
            - "$HOME/.Xauthority:/root/.Xauthority:rw"
        environment:
            NVIDIA_VISIBLE_DEVICES: all
            NVIDIA_DRIVER_CAPABILITIES: all
            DISPLAY: unix:1
        runtime: nvidia
        restart: unless-stopped
        depends_on:
            - reconstruction_kafka
        networks:
            - reconstruction_network

networks:
    reconstruction_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.10.10.0/27
                  gateway: 10.10.10.1

volumes:
    reconstruction_kafka_data:
        driver: local
    reconstruction_zookeeper_data:
        driver: local
    reconstruction_zookeeper_datalog:
        driver: local
  
