//
// Created by valera on 02.03.2021.
//

#ifndef INC_3D_RECONSTRUCTION_NVJPEGIMAGEENCODER_H
#define INC_3D_RECONSTRUCTION_NVJPEGIMAGEENCODER_H


class NvJPEGImageEncoder {

};


#endif //INC_3D_RECONSTRUCTION_NVJPEGIMAGEENCODER_H
