//
// Created by valera on 02.03.2021.
//

#ifndef INC_3D_RECONSTRUCTION_NVJPEG2KIMAGEENCODER_H
#define INC_3D_RECONSTRUCTION_NVJPEG2KIMAGEENCODER_H


class NvJPEG2kImageEncoder {

};


#endif //INC_3D_RECONSTRUCTION_NVJPEG2KIMAGEENCODER_H
