//
// Created by valera on 02.03.2021.
//

#ifndef INC_3D_RECONSTRUCTION_OPENCVIMAGEENCODER_H
#define INC_3D_RECONSTRUCTION_OPENCVIMAGEENCODER_H


class OpenCVImageEncoder {

};


#endif //INC_3D_RECONSTRUCTION_OPENCVIMAGEENCODER_H
